FROM docker.io/golang:1.26.2-alpine AS build

WORKDIR /src/
RUN apk add git
COPY go.* .
RUN go mod download

COPY logging logging
COPY redis redis
COPY types types
COPY dashboard dashboard

COPY *.go .
RUN go build -v -o serge-dashboard-handler

FROM docker.io/alpine
RUN apk add --no-cache tzdata
ENV TZ=America/Chicago
RUN cp /usr/share/zoneinfo/America/Chicago /etc/localtime

COPY --from=build /src/serge-dashboard-handler /serge-dashboard-handler

ENTRYPOINT [ "/serge-dashboard-handler" ]