services:
  redis:
    image: redis:7
    container_name: redis-serge-networking
    ports:
      - "6379:6379"
    networks:
      - serge-external-network
  serge-api-handler:
    extends: 
      file: ./APIHandler/docker-compose.yaml
      service: serge-api-handler


networks:
  serge-external-network:
    external: true