services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - serge-external-network
  serge-api-handler:
    build: 
      context: .
      dockerfile: Containerfile
    container_name: serge-api-handler
    ports:
      - "47009:47009"
    env_file:
      - .env
    networks:
      - serge-external-network

networks:
  serge-external-network:
    external: true